### ISSUE TITLE
Dashboard favorite item star is too big

### ISSUE THREAD

**Issue by kevinhinterlong** [yahoo/navi#549]
**Describe the bug**
The star has a different font-size compared to the other icons in the header

**To Reproduce**
1. Go to https://yahoo.github.io/navi/#/dashboards/1/view
2. The star in the header is too big

**Expected behavior**
It should have the same font-size as the pencil

**Screenshots**
![Screen Shot 2019-10-03 at 4 59 47 PM](https://user-images.githubusercontent.com/12093492/66167344-7c84a600-e5ff-11e9-8029-e49bf8d35cfe.png)

**Comment by objNameGit** [comment]
can i take this task?
Do I understand correctly, the star should be the same size as a pencil?

**Comment by kevinhinterlong** [comment]
All yours! And yep that's right

**Comment by objNameGit** [comment]
Sorry, but i can't commit. I have error 
husky > pre-commit (node v10.16.2)
�🔍  Finding changed files since git revision 6390546
�🎯  Found 0 changed file
✅  Everything is awesome!
Ошибка в синтаксисе команды.
husky > pre-commit hook failed (add --no-verify to bypass)

but 1 file has changed

**Comment by kevinhinterlong** [comment]
Ah you're most likely running into an error with our commit message check.

Make sure to write your commit message in the form `Update: Dashboard star size`
- Starts with `Update:`
- Next word `Dashboard` is capitalized

If it still doesn't work do `git commit -n`

**Comment by objNameGit** [comment]
Thanks for the answer. I read the documentation. But the problem was not solved. What did I do wrong?

git commit -m 'Update: Dashboard star size (fixes #549)'
husky > pre-commit (node v10.16.2)
�🎯  Finding changed files since git revision 6390546
�🎯  Found 0 changed file
✅  Everything is awesome!
Ошибка в синтаксисе команды.
husky > pre-commit hook failed (add --no-verify to bypass)

git commit -n
hint: Waiting for your editor to close the file... "...\Local\Programs\Microsoft VS Code\Code.exe" --wait: ...\Local\Programs\Microsoft VS Code\Code.exe: No such file or directory
error: There was a problem with the editor '"...\Local\Programs\Microsoft VS Code\Code.exe" --wait'.
Please supply the message using either -m or -F option.

**Comment by kevinhinterlong** [comment]
Hmm, I'm not sure why `git commit -m 'Update: Dashboard star size (fixes #549)'` failed

the `git commit -n` skips the verify part, but it looks like the editor didn't give you a place to fill in the commit message since it said
> Please supply the message using either -m or -F option.

So you should be able to manually supply the message `-m` and skip the verify `-n` at the same time with this
```bash
git commit -m 'Update: Dashboard star size (fixes #549)' -n
```

**Comment by objNameGit** [comment]
@kevinhinterlong, great,  git commit -m 'Update: Dashboard star size (fixes #549)' -n 
it work!

**Comment by kevinhinterlong** [comment]
Hey just wanted to check in here, seems like you never pushed your changes/made a PR

**Comment by objNameGit** [comment]
Sorry for the delay, I decided to check the solution again.
